version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - run:
      name: Install Dependencies
      command: |
        pip install selenium

      - run: python explicit_wait.py


  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python explicit_wait.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build


